### ISSUE TITLE
No results returned when filter is given

### ISSUE THREAD

**Issue by mheppner** [inonit/drf-haystack#83] opened 2016-11-14 04:10 UTC
Before I upgraded to Django 1.10 and to the latest versions of Haystack, DRF-Haystack, and Elasticsearch 1.x, I had this setup working. Now I can't get any results from DRF-Haystack when a filter is applied. I have no idea where to begin debugging this, so here are the basics:

```
Django==1.10.3
django-filter==0.15.3
django-haystack==2.5.1
djangorestframework==3.5.3
drf-haystack==1.6.0
elasticsearch==1.9.0
python-dateutil==2.6.0
```

```python
# search_indexes.py
class FooIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    id = indexes.IntegerField(model_attr='id')
    name = indexes.CharField(model_attr='name')
    category = indexes.CharField(model_attr='category__name')
    description = indexes.CharField(model_attr='description')
    autocomplete = indexes.EdgeNgramField()

    @staticmethod
    def prepare_autocomplete(obj):
        return "/".join((
            obj.category.name, obj.name
        ))

    def get_model(self):
        return FooModel

    def index_queryset(self, using=None):
        return self.get_model().objects.all()
```

```python
# views.py
class PortSearchSerializer(HaystackSerializer):
    class Meta:
        index_classes = [FooIndex]
        fields = [
            'text',
            'id',
            'name',
            'category',
            'description',
            'autocomplete',
        ]

class FooViewSet(HaystackViewSet):
    index_models = [Foo]
    serializer_class = FooSearchSerializer
    filter_backends = [HaystackAutocompleteFilter]
    pagination_class = DefaultPagination
    permission_classes = [permissions.AllowAny]
```

I can verify that the index has been populated:
```python
>>> from haystack.query import SearchQuerySet
>>> sqs = SearchQuerySet().all()
>>> sqs.count()
34634
```

Using the viewset without any params  (`/api/search/`) shows me the models serialized as expected and the pagination count matches the index count above. When I add any filter with any text, the results are always 0:
- `/api/search/?autocomplete=test`
- `/api/search/?name=test`
- `/api/search/?name__startswith=test`

I tried adding a breakpoint to [`filters.HaystackAutocompleteFilter.process_filters()`](https://github.com/inonit/drf-haystack/blob/v1.6.0/drf_haystack/filters.py#L105) and it seems like it's getting called twice. The first call has the `filters` set, the second time it's an empty list. Is this normal? I'm not sure where else to look.

**Comment by rhblind** [comment] 2016-11-14 09:38
Hi, thanks for reporting.
That sounds really weird. I'll see if I can reproduce..

**Comment by rhblind** [comment] 2016-11-14 09:54
Hm, did some testing on the [MockApp](https://github.com/inonit/drf-haystack/tree/master/tests/mockapp) now, but cannot reproduce the issue. Have you tried to rebuild the index after upgrading `django-haystack`?

**Comment by mheppner** [comment] 2016-11-14 13:33
I did rebuild the index, and even tried reinstalling Elasticsearch itself. Back in the Python shell, I can do this:
```python
>>> s = SearchQuerySet()
>>> s.filter(name='text').count()
5
```

It seems like Haystack is doing it's thing, it just seems to be that those filters are getting applied incorrectly within DRF-Haystack.

For the `HaystackAutocompleteFilter.process_filters()`, it first gets called with a `filters` param of `(OR: (u'autocomplete', u't'), (u'autocomplete', u'e'), (u'autocomplete', u'x'), (u'autocomplete', u't'))` and the return value becomes `(AND: (u'autocomplete', u't'), (u'autocomplete', u'e'), (u'autocomplete', u's'), (u'autocomplete', u't'))`. But then it gets called a second time with a `filters` arg of `[]`, returning immediately. This happens within one request.

Is there another place I can check to see where it's applying the filters on the queryset? Thanks for your help!

**Comment by rhblind** [comment] 2016-11-18 12:53
Hi again.
I'm sorry but I'm not able to reproduce this issue. Can you provide a unittest or a small test project that illustrates the issue?

**Comment by mheppner** [comment] 2016-11-20 06:06
Hm. I was using Pypy 5.4.1 (Python 2.7.10-compatible) and got this issue. I just switched to a CPython virtualenv, with the exact same versions of dependencies in my `requirements.txt`, and it's working as expected. I've been using the Pypy virtualenv for quite some time now and this problem only happened after I upgraded to Django 1.10 and the new release of DRF-Haystack. I guess I'll keep debugging this to figure out what's going on.

**Comment by mheppner** [comment] 2016-11-20 06:12
There's an obvious difference in the args sent to `HaystackAutocompleteFilter.process_filters()`. With pypy, I had what you see above for `filters`, with each letter being separated by an OR. With cpython, the `filters` arg is set to `(AND: (u'autocomplete', u'test'))`, the single value.

**Comment by rhblind** [comment] 2016-11-21 13:07
Good job, great findings!
Yeah, I'd file a report to Django at least to make the aware of the issue.
I'll close this issue, as the problem seems to lie with Django.

**Closed by rhblind** 2016-11-21 13:07 UTC

**Comment by mheppner** [comment] 2016-11-22 03:29
I reported it to [Django](https://code.djangoproject.com/ticket/27521#ticket). Sorry about the confusion!
