### ISSUE TITLE
Pagination does not works

### ISSUE THREAD

**Issue by rombr** [inonit/drf-haystack#34] opened 2016-02-01 14:14 UTC
When I am opening next page, I receive 404 error.

```
Django==1.7.11
django-haystack==2.4.1
elasticsearch==1.9.0
drf-haystack==1.5.6

Python 2.7.3
Elasticsearch 1.1.2
```

Example code:
```
class SearchSerializer(HaystackSerializer):
    class Meta:
        index_classes = [SomeIndex1, SomeIndex2]

        field_aliases = {
            "query": "text"
        }


class SearchViewSet(HaystackViewSet):
    serializer_class = SearchSerializer
    filter_backends = [HaystackHighlightFilter]

```
Default pagination_class `PageNumberPagination`

As a solution I discovered that need to add `exclude = ('page', 'per_page', )` into SearchSerializer.
Please, fix it or if it normal add to the docs.

**Comment by rhblind** [comment] 2016-02-01 16:25
Thanks for the report, I'll look into it!

**Comment by rhblind** [comment] 2016-02-01 23:42
Hi, just wrote a few test cases to try this out and they passed just fine.
Can you please explain with a bit more detail what the problem is?

A traceback would also be helpful =)

**Comment by rhblind** [comment] 2016-02-06 18:58
Closing with invalid due to missing information.

**Comment by rombr** [comment] 2016-02-11 14:28
Sorry for late answer.
When I did debug with `pdb` my  queryset become empty after applying `HaystackHighlightFilter` https://github.com/inonit/drf-haystack/blob/v1.5.6/drf_haystack/filters.py#L228

It seems like `page` and `per_page` GET params becomes terms for ES filter and ES does not find anything because no such fields in `SomeIndex1` and `SomeIndex2`

And only `exclude = ('page', 'per_page', )` helped me.

**Comment by rhblind** [comment] 2016-02-11 23:09
Alright, thanks.
I'll reopen and investigate a bit further =)

**Comment by gilsondev** [comment] 2016-03-10 23:29
So, the pagination not really works?

**Comment by rhblind** [comment] 2016-03-10 23:48
I have not experienced issues with pagination, but I have not had the time to dig into this issue yet.

**Comment by rhblind** [comment] 2016-04-24 18:15
Due to lack of follow ups on this I'll close it.

**Closed by rhblind** 2016-04-24 18:15 UTC
